### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by henriqueelder** [popey/spek-snap#1]
Hello. Could you do a flatpak build for this app? I use Endless OS and just can install flatpaks. Would be great this app available the all linux distributions. Thank you so much.

**Comment by popey** [comment]
The reason I packaged spek as a snap is because it's not available in Ubuntu beyond 18.04. It's effectively abandoned upstream and I wanted to install it on a newer release. The snap is in use by around 750 users across 20 distros (7 Ubuntu, 13 non-Ubuntu). I don't see any value for me in making a flatpak of it to support one more distro, which will likely have very few users. Sorry, maybe someone else can do that.
